version: '3.8'

services:
  api:
    build: 
      context: ./packages/api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://flowbit:flowbit123@cluster0.ehbfyyy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=flowbit-super-secret-key-2024
      - N8N_WEBHOOK_SECRET=n8n-flowbit-shared-secret-2024
      - NGROK_AUTH_TOKEN=2zylfJOfTEEgG3ZlbvBmhlYMJ7I_4C9YvuFtApG5ZnxCvPekn
    depends_on:
      - n8n
    volumes:
      - ./packages/api:/app
      - /app/node_modules

  shell:
    build:
      context: ./packages/shell
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./packages/shell:/app
      - /app/node_modules

  support-tickets:
    build:
      context: ./packages/support-tickets
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./packages/support-tickets:/app
      - /app/node_modules

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://host.docker.internal:3001
    volumes:
      - n8n_data:/home/node/.n8n

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=2zylfJOfTEEgG3ZlbvBmhlYMJ7I_4C9YvuFtApG5ZnxCvPekn

volumes:
  n8n_data: